//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meatyceiver2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meatyceiver2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures - Ammo.
        /// </summary>
        internal static string AmmoFailures_section {
            get {
                return ResourceManager.GetString("AmmoFailures.section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures - Bespoke.
        /// </summary>
        internal static string BespokeFailure {
            get {
                return ResourceManager.GetString("BespokeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Action failure to eject rate.
        /// </summary>
        internal static string BreakActionFTE_key {
            get {
                return ResourceManager.GetString("BreakActionFTE.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Action Failure To Eject General Multiplier Affect.
        /// </summary>
        internal static string BreakActionFTEMult_key {
            get {
                return ResourceManager.GetString("BreakActionFTEMult.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures - Broken Firearm.
        /// </summary>
        internal static string BrokenFirearmFailure {
            get {
                return ResourceManager.GetString("BrokenFirearmFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug ;).
        /// </summary>
        internal static string DEBUG {
            get {
                return ResourceManager.GetString("DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Feed Rate.
        /// </summary>
        internal static string DFRate_key {
            get {
                return ResourceManager.GetString("DFRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables ammunition related failures..
        /// </summary>
        internal static string EnableAmmunitionFailures_description {
            get {
                return ResourceManager.GetString("EnableAmmunitionFailures.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Ammunition Failures.
        /// </summary>
        internal static string EnableAmmunitionFailures_key {
            get {
                return ResourceManager.GetString("EnableAmmunitionFailures.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables failures related to permanent firearm damage..
        /// </summary>
        internal static string EnableBrokenFirearmFailures_description {
            get {
                return ResourceManager.GetString("EnableBrokenFirearmFailures.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Broken Firearm Failures.
        /// </summary>
        internal static string EnableBrokenFirearmFailures_key {
            get {
                return ResourceManager.GetString("EnableBrokenFirearmFailures.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Console Debugging. Default false.
        /// </summary>
        internal static string EnableConsoleDebugging_description {
            get {
                return ResourceManager.GetString("EnableConsoleDebugging.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Console Debugging.
        /// </summary>
        internal static string EnableConsoleDebugging_key {
            get {
                return ResourceManager.GetString("EnableConsoleDebugging.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable firearm related failures..
        /// </summary>
        internal static string EnableFirearmFailures_description {
            get {
                return ResourceManager.GetString("EnableFirearmFailures.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Firearm Failures.
        /// </summary>
        internal static string EnableFirearmFailures_key {
            get {
                return ResourceManager.GetString("EnableFirearmFailures.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures - Firearm.
        /// </summary>
        internal static string FirearmFailures_section {
            get {
                return ResourceManager.GetString("FirearmFailures.section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Multiplier is multiplied by this before affecting BA FTE..
        /// </summary>
        internal static string FTEMult_description {
            get {
                return ResourceManager.GetString("FTEMult.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to Eject rate.
        /// </summary>
        internal static string FTERate_key {
            get {
                return ResourceManager.GetString("FTERate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to Feed Rate.
        /// </summary>
        internal static string FTFRate_key {
            get {
                return ResourceManager.GetString("FTFRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to Lock Slide Rate.
        /// </summary>
        internal static string FTLSlide_key {
            get {
                return ResourceManager.GetString("FTLSlide.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default is at 1x is 1%, so this is a more &quot;pick failure percentage chance&quot;..
        /// </summary>
        internal static string GeneralMultipliers_description {
            get {
                return ResourceManager.GetString("GeneralMultipliers.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Chance Multiplier.
        /// </summary>
        internal static string GeneralMultipliers_key {
            get {
                return ResourceManager.GetString("GeneralMultipliers.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipliers.
        /// </summary>
        internal static string GeneralMultipliers_section {
            get {
                return ResourceManager.GetString("GeneralMultipliers.section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang Fire Rate.
        /// </summary>
        internal static string HangFireRate_key {
            get {
                return ResourceManager.GetString("HangFireRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer Follow Rate.
        /// </summary>
        internal static string HFRate_key {
            get {
                return ResourceManager.GetString("HFRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i hvaent implemented it yet, but it&apos;s basically the gun jams more often the more rounds you put thru it.
        /// </summary>
        internal static string LongTermBreak_description {
            get {
                return ResourceManager.GetString("LongTermBreak.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Long Term Breakdown.
        /// </summary>
        internal static string LongTermBreak_key {
            get {
                return ResourceManager.GetString("LongTermBreak.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Failure - Long Term Breakdown.
        /// </summary>
        internal static string LongTermBreak_section {
            get {
                return ResourceManager.GetString("LongTermBreak.section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Primer Strike Failure Rate.
        /// </summary>
        internal static string LPSRate_key {
            get {
                return ResourceManager.GetString("LPSRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables mag unreliability chance multipliers.
        /// </summary>
        internal static string MagReliability_description {
            get {
                return ResourceManager.GetString("MagReliability.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mag Unreliability.
        /// </summary>
        internal static string MagReliability_key {
            get {
                return ResourceManager.GetString("MagReliability.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every round in a mag past Minimum Mag Count increases FTF failure percent chance this much. Separate from General Multiplier..
        /// </summary>
        internal static string MagReliabilityMult_description {
            get {
                return ResourceManager.GetString("MagReliabilityMult.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Unreliability Multiplier.
        /// </summary>
        internal static string MagReliabilityMult_key {
            get {
                return ResourceManager.GetString("MagReliabilityMult.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Failure - Mag Unreliability.
        /// </summary>
        internal static string MagUnreliability_section {
            get {
                return ResourceManager.GetString("MagUnreliability.section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max mag round counts above this incurs higher unreliability..
        /// </summary>
        internal static string MagUnreliabilityMult_description {
            get {
                return ResourceManager.GetString("MagUnreliabilityMult.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Unreliability General Multiplier Affect.
        /// </summary>
        internal static string MagUnreliabilityMult_key {
            get {
                return ResourceManager.GetString("MagUnreliabilityMult.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max mag round counts above this incurs higher unreliability..
        /// </summary>
        internal static string MinRoundCount_description {
            get {
                return ResourceManager.GetString("MinRoundCount.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Mag Count.
        /// </summary>
        internal static string MinRoundCount_key {
            get {
                return ResourceManager.GetString("MinRoundCount.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolver Failure to eject rate.
        /// </summary>
        internal static string RevolverFTE_key {
            get {
                return ResourceManager.GetString("RevolverFTE.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolver Failure To Eject General Multiplier Affect.
        /// </summary>
        internal static string RevolverFTERate_key {
            get {
                return ResourceManager.GetString("RevolverFTERate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slam Fire Rate.
        /// </summary>
        internal static string SlamFireRate_key {
            get {
                return ResourceManager.GetString("SlamFireRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stovepipe Lerp.
        /// </summary>
        internal static string StovepipeLerp_key {
            get {
                return ResourceManager.GetString("StovepipeLerp.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stovepipe Rate.
        /// </summary>
        internal static string StovepipeRate_key {
            get {
                return ResourceManager.GetString("StovepipeRate.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid input: Float, 0f - 100f.
        /// </summary>
        internal static string ValidInput_float {
            get {
                return ResourceManager.GetString("ValidInput.float", resourceCulture);
            }
        }
    }
}
